In [11]:
import numpy as np
import pandas as pd


In [12]:
df = pd.read_csv('../../data/vgsales.csv')
df.head()

Rank                      Name Platform    Year         Genre Publisher   
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo  \
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [2]:
pd.__version__

'2.0.1'

In [13]:
df['Name'].values

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii', ...,
       'SCORE International Baja 1000: The Official Game', 'Know How 2',
       'Spirits & Spells'], dtype=object)

In [5]:
df['Platform'].values

array(['Wii', 'NES', 'Wii', ..., 'PS2', 'DS', 'GBA'], dtype=object)

In [7]:
df['Genre'].values

array(['Sports', 'Platform', 'Racing', ..., 'Racing', 'Puzzle',
       'Platform'], dtype=object)

In [8]:
df['Publisher'].values

array(['Nintendo', 'Nintendo', 'Nintendo', ..., 'Activision', '7G//AMES',
       'Wanadoo'], dtype=object)

In [9]:
df['Global_Sales'].values

array([8.274e+01, 4.024e+01, 3.582e+01, ..., 1.000e-02, 1.000e-02,
       1.000e-02])

In [14]:
platforms = df['Platform'].values
platforms

array(['Wii', 'NES', 'Wii', ..., 'PS2', 'DS', 'GBA'], dtype=object)

In [16]:
total_sales = df['Global_Sales'].values
total_sales

array([8.274e+01, 4.024e+01, 3.582e+01, ..., 1.000e-02, 1.000e-02,
       1.000e-02])

In [15]:
unique_platforms = np.unique(platforms)
unique_platforms


array(['2600', '3DO', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'GG',
       'N64', 'NES', 'NG', 'PC', 'PCFX', 'PS', 'PS2', 'PS3', 'PS4', 'PSP',
       'PSV', 'SAT', 'SCD', 'SNES', 'TG16', 'WS', 'Wii', 'WiiU', 'X360',
       'XB', 'XOne'], dtype=object)

In [17]:
total_sales_platform = []
for platform in unique_platforms:
    total_sales_platform.append (np.sum(total_sales[platforms == platform]))
    
total_sales_platform = np.array(total_sales_platform)
total_sales_platform

array([9.70800e+01, 1.00000e-01, 2.47460e+02, 1.59700e+01, 8.22490e+02,
       2.55450e+02, 3.18500e+02, 1.99360e+02, 2.83600e+01, 4.00000e-02,
       2.18880e+02, 2.51070e+02, 1.44000e+00, 2.58820e+02, 3.00000e-02,
       7.30660e+02, 1.25564e+03, 9.57840e+02, 2.78100e+02, 2.96280e+02,
       6.19300e+01, 3.35900e+01, 1.87000e+00, 2.00050e+02, 1.60000e-01,
       1.42000e+00, 9.26710e+02, 8.18600e+01, 9.79960e+02, 2.58260e+02,
       1.41060e+02])

In [18]:
[np.sum(total_sales[platforms == platform]) for platform in unique_platforms]

[97.07999999999998,
 0.1,
 247.46,
 15.969999999999999,
 822.49,
 255.45000000000002,
 318.5,
 199.35999999999999,
 28.36,
 0.04,
 218.88,
 251.07,
 1.4400000000000002,
 258.82,
 0.03,
 730.66,
 1255.6399999999999,
 957.84,
 278.1,
 296.28000000000003,
 61.930000000000014,
 33.59,
 1.8700000000000003,
 200.05,
 0.16,
 1.42,
 926.71,
 81.86000000000001,
 979.96,
 258.26,
 141.06]