In [2]:
import numpy as np

In [96]:
np.__version__

'1.24.3'

## CREACION DE ARRAYS


In [97]:
numbers = [1, 2, 3, 4]
numbers

[1, 2, 3, 4]

In [98]:
arr = np.array([1, 4, 2, 5, 3])
arr

array([1, 4, 2, 5, 3])

In [99]:
type(arr)

numpy.ndarray

In [100]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [101]:
numbers_tuple = (1,2,3)
numbers_list = list(numbers_tuple)
numbers

[1, 2, 3, 4]

In [102]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## ATRIBUTOS DE ARRAYS

In [103]:
np.random.seed(0) # seed for reproducibility

In [104]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [105]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [106]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [107]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [108]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int32
itemsize: 4 bytes
nbytes: 48 bytes


In [109]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [110]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## Acceder a los elementos: indexación

In [111]:
x1  # array de 1 dimensión

array([5, 0, 3, 3, 7, 9])

In [112]:
print(x1[0])
print(x1[1])
print(x1[2])

5
0
3


In [113]:
print(x1[-1])
print(x1[-2])
print(x1[-3])

9
7
3


In [114]:
x2  # array de 2 dimensiones

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [115]:
print(x2[0,0])
print(x2[0,1])
print(x2[0,2])
print(x2[0,3])
print(x2[1,0])
print(x2[1,1])
print(x2[1,2])
print(x2[2,3])

3
5
2
4
7
6
8
7


In [116]:
x3[0,0,0]

8

In [117]:
8

8

In [118]:
x2[0][0]

3

In [119]:
print(x2[0,-1])

4


In [120]:
x2.dtype

dtype('int32')

In [121]:
print("Valor original:", x2[0,0])
x2[0,0] = 8.9
print("Valor modificado:", x2[0,0])

Valor original: 3
Valor modificado: 8


Acceder a subarrays: slicing

In [122]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
x[::2] # start, stop, step

array([0, 2, 4, 6, 8])

In [125]:
print(x[:5])  # start, stop, step
print(x[5:])
print(x[3:7])

[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5 6]


In [126]:
print(x[::2])
print(x[1::2])
print(x[::-1])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [127]:
x2

array([[8, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [128]:
x2[:2, 1:3]

array([[5, 2],
       [6, 8]])

In [129]:
x2[:2, ::2]

array([[8, 2],
       [7, 8]])

In [130]:
print(x2[:, 0])
print(x2[0, :])

[8 7 1]
[8 5 2 4]


## Copy vs. view

In [131]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [132]:
x2_sub = x2[:2, :2]  # técnica slicing
x2_sub

array([[4, 3],
       [8, 4]])

In [133]:
x2_sub[0, 0] = 99  # Al modificar en uno se modifica en los dos

In [134]:
print(x2)
print('\n')
print(x2_sub)

[[99  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


[[99  3]
 [ 8  4]]


In [135]:
x2_sub_copy = x2[:2, :2].copy()  # método copy() para crear una copia independiente

In [136]:
x2_sub_copy[0, 0] = 50

In [137]:
print(x2)
print('\n')
print(x2_sub_copy)

[[99  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


[[50  3]
 [ 8  4]]


## Redimensionar un array (reshape)

In [138]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [139]:
x.ndim

1

In [140]:
x.shape

(9,)

In [141]:
type(x.shape)

tuple

In [142]:
x_2d = x.reshape((3, 3))
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [143]:
x_2d.ndim

2

In [144]:
print(x.reshape((1, 9)))  # 2 dimensiones: 1 fila y 9 columnas

[[1 2 3 4 5 6 7 8 9]]


In [145]:
x.reshape((1, 9)).ndim

2

## np.newaxis

In [146]:
print(x); print(x.ndim); print(x.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)


In [147]:
y = x[np.newaxis, :]; print(y); print(y.ndim); print(y.shape)

[[1 2 3 4 5 6 7 8 9]]
2
(1, 9)


In [148]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [149]:
arr.shape

(4,)

In [150]:
row_vec = arr[np.newaxis]
row_vec

array([[0, 1, 2, 3]])

In [151]:
row_vec.shape

(1, 4)

In [152]:
col_vec = arr[:, np.newaxis] 
col_vec

array([[0],
       [1],
       [2],
       [3]])

In [153]:
col_vec.shape

(4, 1)

In [154]:
arr[np.newaxis, np.newaxis, :]

array([[[0, 1, 2, 3]]])

In [155]:
arr[:, np.newaxis, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]]])

## ravel

In [156]:
x = np.array([1, 2, 3, 4, 5])
print(x); print(np.ravel(x))

[1 2 3 4 5]
[1 2 3 4 5]


In [157]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [158]:
print(np.ravel(x))
print(np.ravel(x).ndim)

[1 2 3 4 5 6]
1


## Concatenar arrays

concatenate

In [159]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = [99, 99, 99]

print(x); print(y); print(z); print('\n')

print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))
print(x)

[1 2 3]
[4 5 6]
[99, 99, 99]


[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]
[1 2 3]


In [160]:
grid = np.array([ [1, 2, 3], [4, 5, 6] ])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [161]:
print("shape", grid.shape); print("dimensiones", grid.ndim)

shape (2, 3)
dimensiones 2


In [162]:
y = np.concatenate([grid, grid])
print(y); print(y.ndim); print(y.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
2
(4, 3)


In [163]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [164]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

vstack

In [165]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [166]:
grid = np.array([ [9, 8, 7], [6, 5, 4] ])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [167]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

hstack

In [168]:
y = np.array([4, 5, 6])
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [169]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [170]:
y = np.array([[99], [99]])
y

array([[99],
       [99]])

In [171]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [172]:
y = np.array([4, 5])
y

array([4, 5])

In [173]:
y = y.reshape(2, 1)
y

array([[4],
       [5]])

In [174]:
np.hstack([grid, y])

array([[9, 8, 7, 4],
       [6, 5, 4, 5]])

Separar arrays (split)

split()

In [175]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [176]:
x1, x2, x3 = np.split(x, [3, 5])
print(x1)
print(x2)
print(x3)

[1 2 3]
[99 99]
[3 2 1]


vsplit()

In [177]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [178]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [179]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [180]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [181]:
upper, lower = np.vsplit(grid, [3])
print(upper)
print('\n')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]]


hsplit()

In [182]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [183]:
left, right = np.hsplit(grid, [2])
print(left)
print('\n')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [184]:
left, right = np.hsplit(grid, [3])
print(left)
print('\n')
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


[[ 3]
 [ 7]
 [11]
 [15]]


## Operaciones sobre arrays

aritméticas

In [185]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [186]:
import numpy as np

In [187]:
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("x ** 2 =", x ** 2)
print("-x = ", -x)
print("x % 2 = ", x % 2)

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
-x =  [ 0 -1 -2 -3]
x % 2 =  [0 1 0 1]


In [188]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [3]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [4]:
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("x ** 2 =", x ** 2)
print("-x = ", -x)
print("x % 2 = ", x % 2)

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
-x =  [ 0 -1 -2 -3]
x % 2 =  [0 1 0 1]


In [5]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [6]:
print(np.arange(5))
print(np.arange(1,6))

[0 1 2 3 4]
[1 2 3 4 5]


In [7]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [8]:
np.arange(5) // np.arange(1, 6)  # División suelo elimina la parte decimal

array([0, 0, 0, 0, 0])

In [9]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [11]:
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

np.absolute

In [12]:
x = np.array([-2, -1, 0, 1, 2])
x

array([-2, -1,  0,  1,  2])

In [13]:
np.absolute(x)  # ``np.abs`` is a shorthand for this function.

array([2, 1, 0, 1, 2])

In [14]:
np.abs(x) 

array([2, 1, 0, 1, 2])

trigonométricas

In [15]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [16]:
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tag(theta) =", np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tag(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [17]:
x = [-1, 0, 1]

In [18]:
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


exponenciales y logarítmicas

In [19]:
x = [1, 2, 3]
x

[1, 2, 3]

In [20]:
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("4^x   =", np.power(4, x))

e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
4^x   = [ 4 16 64]


In [21]:
x = [1, 2, 4, 10]
x

[1, 2, 4, 10]

In [22]:
print("ln(x)   =", np.log(x))
print("ln2(x)   =", np.log2(x))
print("ln10(x)   =", np.log10(x))

ln(x)   = [0.         0.69314718 1.38629436 2.30258509]
ln2(x)   = [0.         1.         2.         3.32192809]
ln10(x)   = [0.         0.30103    0.60205999 1.        ]


In [23]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [24]:
y = np.empty(5) 
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [25]:
y

array([ 0., 10., 20., 30., 40.])

reduce

In [26]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [27]:
x + 5

array([ 6,  7,  8,  9, 10])

In [28]:
np.add(x, 5)

array([ 6,  7,  8,  9, 10])

In [29]:
cont = 0
for i in x:
    cont += i; print(cont)

1
3
6
10
15


In [30]:
np.add.reduce(x)  # lo mismo que lo anterior pero más óptimo

15

In [31]:
np.multiply.reduce(x)

120

accumulate

In [32]:
x

array([1, 2, 3, 4, 5])

In [33]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [34]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

outer()

In [35]:
print(x)

[1 2 3 4 5]


In [36]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

min(), max(), sum()

In [37]:
big_array = np.random.rand(10000)

In [38]:
np.min(big_array)

0.00013436454393389585

In [39]:
np.max(big_array)

0.9999748520249003

In [40]:
matrix = np.random.random((3, 4))
matrix

array([[0.00690889, 0.88081613, 0.43857457, 0.96709748],
       [0.02143278, 0.13179909, 0.28805997, 0.55809716],
       [0.01164307, 0.21804015, 0.64790013, 0.62711169]])

In [41]:
matrix.sum()

4.797481124355523

In [42]:
matrix.min()

0.0069088861648325395

In [43]:
matrix.min(axis=0)

array([0.00690889, 0.13179909, 0.28805997, 0.55809716])

In [44]:
matrix.min(axis=1)

array([0.00690889, 0.02143278, 0.01164307])