In [12]:
import numpy as np

In [13]:
np.__version__

'1.24.3'

## CREACION DE ARRAYS


In [6]:
numbers = [1, 2, 3, 4]
numbers

[1, 2, 3, 4]

In [7]:
arr = np.array([1, 4, 2, 5, 3])
arr

array([1, 4, 2, 5, 3])

In [ ]:
type(arr)

In [8]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
numbers_tuple = (1,2,3)
numbers_list = list(numbers_tuple)
numbers

[1, 2, 3, 4]

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## ATRIBUTOS DE ARRAYS

In [15]:
np.random.seed(0) # seed for reproducibility

In [16]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int32
itemsize: 4 bytes
nbytes: 48 bytes


In [21]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [22]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## Acceder a los elementos: indexación

In [23]:
x1  # array de 1 dimensión

array([5, 0, 3, 3, 7, 9])

In [24]:
print(x1[0])
print(x1[1])
print(x1[2])

5
0
3


In [25]:
print(x1[-1])
print(x1[-2])
print(x1[-3])

9
7
3


In [26]:
x2  # array de 2 dimensiones

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
print(x2[0,0])
print(x2[0,1])
print(x2[0,2])
print(x2[0,3])
print(x2[1,0])
print(x2[1,1])
print(x2[1,2])
print(x2[2,3])

3
5
2
4
7
6
8
7


In [28]:
x3[0,0,0]

8

In [29]:
8

8

In [30]:
x2[0][0]

3

In [31]:
print(x2[0,-1])

4


In [32]:
x2.dtype

dtype('int32')

In [34]:
print("Valor original:", x2[0,0])
x2[0,0] = 8.9
print("Valor modificado:", x2[0,0])

Valor original: 3
Valor modificado: 8


Acceder a subarrays: slicing

In [35]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x[::2] # start, stop, step

array([0, 2, 4, 6, 8])

In [38]:
print(x[:5])  # start, stop, step
print(x[5:])
print(x[3:7])

[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5 6]


In [39]:
print(x[::2])
print(x[1::2])
print(x[::-1])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [40]:
x2

array([[8, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[:2, 1:3]

array([[5, 2],
       [6, 8]])

In [42]:
x2[:2, ::2]

array([[8, 2],
       [7, 8]])

In [45]:
print(x2[:, 0])
print(x2[0, :])

[8 7 1]
[8 5 2 4]


## Copy vs. view

In [46]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [47]:
x2_sub = x2[:2, :2]  # técnica slicing
x2_sub

array([[4, 3],
       [8, 4]])

In [48]:
x2_sub[0, 0] = 99  # Al modificar en uno se modifica en los dos

In [49]:
print(x2)
print('\n')
print(x2_sub)

[[99  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


[[99  3]
 [ 8  4]]


In [51]:
x2_sub_copy = x2[:2, :2].copy()  # método copy() para crear una copia independiente

In [52]:
x2_sub_copy[0, 0] = 50

In [53]:
print(x2)
print('\n')
print(x2_sub_copy)

[[99  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


[[50  3]
 [ 8  4]]


## Redimensionar un array (reshape)

In [54]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [55]:
x.ndim

1

In [56]:
x.shape

(9,)

In [57]:
type(x.shape)

tuple

In [58]:
x_2d = x.reshape((3, 3))
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
x_2d.ndim

2

In [60]:
print(x.reshape((1, 9)))  # 2 dimensiones: 1 fila y 9 columnas

[[1 2 3 4 5 6 7 8 9]]


In [61]:
x.reshape((1, 9)).ndim

2

## np.newaxis

In [62]:
print(x); print(x.ndim); print(x.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)


In [63]:
y = x[np.newaxis, :]; print(y); print(y.ndim); print(y.shape)

[[1 2 3 4 5 6 7 8 9]]
2
(1, 9)


In [64]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [65]:
arr.shape

(4,)

In [66]:
row_vec = arr[np.newaxis]
row_vec

array([[0, 1, 2, 3]])

In [67]:
row_vec.shape

(1, 4)

In [68]:
col_vec = arr[:, np.newaxis] 
col_vec

array([[0],
       [1],
       [2],
       [3]])

In [69]:
col_vec.shape

(4, 1)

In [70]:
arr[np.newaxis, np.newaxis, :]

array([[[0, 1, 2, 3]]])

In [71]:
arr[:, np.newaxis, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]]])

## ravel

In [72]:
x = np.array([1, 2, 3, 4, 5])
print(x); print(np.ravel(x))

[1 2 3 4 5]
[1 2 3 4 5]


In [73]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [74]:
print(np.ravel(x))
print(np.ravel(x).ndim)

[1 2 3 4 5 6]
1


## Concatenar arrays

concatenate

In [75]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = [99, 99, 99]

print(x); print(y); print(z); print('\n')

print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))
print(x)

[1 2 3]
[4 5 6]
[99, 99, 99]


[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]
[1 2 3]


In [76]:
grid = np.array([ [1, 2, 3], [4, 5, 6] ])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
print("shape", grid.shape); print("dimensiones", grid.ndim)

shape (2, 3)
dimensiones 2


In [78]:
y = np.concatenate([grid, grid])
print(y); print(y.ndim); print(y.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
2
(4, 3)


In [79]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

vstack

In [81]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [82]:
grid = np.array([ [9, 8, 7], [6, 5, 4] ])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [83]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

hstack

In [84]:
y = np.array([4, 5, 6])
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [85]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [86]:
y = np.array([[99], [99]])
y

array([[99],
       [99]])

In [87]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [88]:
y = np.array([4, 5])
y

array([4, 5])

In [89]:
y = y.reshape(2, 1)
y

array([[4],
       [5]])

In [90]:
np.hstack([grid, y])

array([[9, 8, 7, 4],
       [6, 5, 4, 5]])

Separar arrays (split)

split()

In [91]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [92]:
x1, x2, x3 = np.split(x, [3, 5])
print(x1)
print(x2)
print(x3)

[1 2 3]
[99 99]
[3 2 1]


vsplit()

In [93]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [96]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [97]:
upper, lower = np.vsplit(grid, [3])
print(upper)
print('\n')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]]


hsplit()

In [98]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
left, right = np.hsplit(grid, [2])
print(left)
print('\n')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [100]:
left, right = np.hsplit(grid, [3])
print(left)
print('\n')
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


[[ 3]
 [ 7]
 [11]
 [15]]


## Operaciones sobre arrays

aritméticas

In [3]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [2]:
import numpy as np

In [4]:
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("x ** 2 =", x ** 2)
print("-x = ", -x)
print("x % 2 = ", x % 2)

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
-x =  [ 0 -1 -2 -3]
x % 2 =  [0 1 0 1]


In [5]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])