In [25]:
import numpy as np


In [26]:
dataset = np.genfromtxt('../data/StudentsPerformance.csv', delimiter=',', skip_header=1, dtype=int)
dataset

array([[-1, -1, -1, ..., 72, 72, 74],
       [-1, -1, -1, ..., 69, 90, 88],
       [-1, -1, -1, ..., 90, 95, 93],
       ...,
       [-1, -1, -1, ..., 59, 71, 65],
       [-1, -1, -1, ..., 68, 78, 77],
       [-1, -1, -1, ..., 77, 86, 86]])

In [27]:
print(dataset.ndim)
print(dataset.shape)

2
(1000, 8)


In [28]:
write_scores = dataset[:, -1]
read_scores = dataset[:, -2]
math_scores = dataset[:, -3]

In [29]:
math_scores.shape

(1000,)

## OPERACIONES ARITMETICAS


SUMATORIO NOTAS

In [30]:
scores = write_scores + read_scores + math_scores
scores[:20]

array([218, 247, 278, 148, 229, 232, 275, 122, 195, 148, 164, 135, 219,
       220, 161, 222, 263,  78, 134, 173])

In [31]:
scores.shape

(1000,)

## NOTA MEDIA

In [32]:
final_scores = scores / 3
final_scores = np.round(final_scores, 0)
final_scores[:20]

array([73., 82., 93., 49., 76., 77., 92., 41., 65., 49., 55., 45., 73.,
       73., 54., 74., 88., 26., 45., 58.])

In [33]:
final_scores.dtype

dtype('float64')

In [34]:
final_scores = final_scores.astype(int)
final_scores[:20]

array([73, 82, 93, 49, 76, 77, 92, 41, 65, 49, 55, 45, 73, 73, 54, 74, 88,
       26, 45, 58])

In [35]:
final_scores.dtype

dtype('int32')

## ORDENAR

In [36]:
final_scores_asc = np.sort(final_scores)
print(f"Nota mas baja: {final_scores_asc[0]}")
print(f"Nota mas alta: {final_scores_asc[-1]}")

Nota mas baja: 9
Nota mas alta: 100


## FILTRAR DATOS

In [37]:
success_scores = final_scores[final_scores >= 50]
fail_scores = final_scores[final_scores < 50]

In [38]:
print(f"success: {success_scores.shape}")
print(f"fail: {fail_scores.shape}")

success: (900,)
fail: (100,)


In [39]:
fail_index = np.where(final_scores < 50)
fail_index

(array([  3,   7,   9,  11,  17,  18,  33,  52,  55,  59,  61,  66,  72,
         74,  75,  76,  80,  81,  84,  91,  93, 131, 136, 143, 145, 174,
        182, 184, 188, 204, 211, 217, 231, 250, 262, 265, 280, 281, 284,
        296, 298, 307, 324, 327, 329, 331, 337, 338, 363, 375, 383, 384,
        395, 401, 424, 448, 455, 466, 527, 528, 552, 554, 555, 564, 565,
        575, 596, 601, 616, 640, 683, 706, 723, 724, 729, 731, 733, 777,
        785, 787, 794, 807, 810, 811, 840, 842, 858, 862, 867, 883, 889,
        895, 896, 902, 910, 921, 928, 978, 980, 988], dtype=int64),)

In [40]:
final_scores[fail_index]

array([49, 41, 49, 45, 26, 45, 40, 46, 39,  9, 37, 40, 47, 46, 41, 26, 49,
       46, 38, 32, 46, 43, 49, 49, 31, 49, 49, 49, 48, 47, 30, 38, 44, 48,
       48, 47, 49, 46, 43, 43, 45, 49, 43, 23, 49, 40, 48, 30, 31, 43, 44,
       41, 45, 46, 38, 45, 47, 32, 44, 39, 46, 46, 35, 48, 45, 49, 23, 29,
       40, 48, 38, 39, 47, 44, 43, 48, 49, 41, 42, 30, 48, 42, 39, 47, 46,
       34, 49, 40, 48, 48, 48, 35, 31, 41, 47, 45, 44, 48, 18, 45])

## ESTADISTICAS

In [41]:
np.mean(final_scores[fail_index])

41.82

In [42]:
np.mean(success_scores)

70.64444444444445

## VALORES CATEGORICOS

In [43]:
import numpy as np