In [1]:
import numpy as np


In [12]:
np.genfromtxt('../data/vgsales.csv' , usecols=(1), dtype=str, skip_header=1, delimiter= ',')


array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii', ...,
       'SCORE International Baja 1000: The Official Game', 'Know How 2',
       'Spirits & Spells'], dtype='<U132')

In [13]:
names = np.genfromtxt('../data/vgsales.csv' , usecols=(1), dtype=str, skip_header=1, delimiter= ',')
names.shape

(16598,)

In [14]:
names = np.genfromtxt('../data/vgsales.csv' , usecols=(1), dtype=str, skip_header=1, delimiter= ',')
names[:5]

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii',
       'Wii Sports Resort', 'Pokemon Red/Pokemon Blue'], dtype='<U132')

In [15]:
platfrom = np.genfromtxt('../data/vgsales.csv' , usecols=(2), dtype=str, skip_header=1, delimiter= ',', invalid_raise=False)
platfrom.shape

(16598,)

In [19]:
year = np.genfromtxt('../data/vgsales.csv' , usecols=(1), dtype=int, skip_header=1, delimiter= ',')
year.shape

(16598,)

In [18]:
geners = np.genfromtxt('../data/vgsales.csv' , usecols=(1), dtype=str, skip_header=1, delimiter= ',')
geners.shape

(16598,)

In [20]:
publishers = np.genfromtxt('../data/vgsales.csv' , usecols=(1), dtype=str, skip_header=1, delimiter= ',')
publishers.shape

(16598,)

In [21]:
sales = np.genfromtxt('../data/vgsales.csv' , usecols=(6,7,8,9), dtype=float, skip_header=1, delimiter= ',')
sales.shape

(16598, 4)

# CALCULAR VENTAS TOTALES

In [25]:
np.set_printoptions(suppress=True)
sales

array([[41.49, 29.02,  3.77,  8.46],
       [29.08,  3.58,  6.81,  0.77],
       [15.85, 12.88,  3.79,  3.31],
       ...,
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ],
       [ 0.01,  0.  ,  0.  ,  0.  ]])

In [23]:
np.sum(sales,axis=1).shape

(16598,)

In [26]:
np.sum(sales, axis=1)

array([82.74, 40.24, 35.83, ...,  0.  ,  0.01,  0.01])

In [27]:
total_sales = np.sum(sales, axis=1)
total_sales

array([82.74, 40.24, 35.83, ...,  0.  ,  0.01,  0.01])

In [30]:
import numpy as np

In [32]:
np.mean(total_sales)

nan

In [ ]:
print(f"{np.mean(total_sales)}")
print(f"{np.mean(total_sales)}")
print(f"{np.mean(total_sales)}")
print(f"{np.mean(total_sales)}")

# DETECTAR SI HAY NAN (valores faltantes)

In [34]:
isnam = np.isnan(total_sales)
isnam[isnam== True]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [38]:
print(f"Hay Nan: {np.isnan(total_sales).any()}")
print(f"Hay Infinito: {np.isinf(total_sales).any()}")
print(f"Hay Infinito Negativo: {np.isneginf(total_sales).any()}")

Hay Nan: True
Hay Infinito: False
Hay Infinito Negativo: False


In [39]:
# CONTAR CUANTOS HAY (NAN)
len(total_sales[np.isnan(total_sales)])

123

In [42]:
# REEMPLAZAR NAN x CERO
total_sales2 = np.nan_to_num(total_sales, nan=0)
print(f"{len(total_sales2)}")
print(f"{np.isnan(total_sales2).any()}") # FALSE


16598
False
